object: orig/D8MJ01/sys/main.dol
hash: 4d2821a6801d8db3b3962d71dfa1e345fcec03e3
symbols: config/D8MJ01/symbols.txt
splits: config/D8MJ01/splits.txt
mw_comment_version: 10 # GC 2.6 linker
modules:
- object: orig/D8MJ01/files/rel/aaa.rel
  hash: e18752e5821f2d9fd8a64bef2c047a73c84cada4
  symbols: config/D8MJ01/aaa/symbols.txt
  splits: config/D8MJ01/aaa/splits.txt
- object: orig/D8MJ01/files/rel/aji.rel
  hash: 1b4e61e72a429a38c42658edb865b7171bfd6a2e
  symbols: config/D8MJ01/aji/symbols.txt
  splits: config/D8MJ01/aji/splits.txt
- object: orig/D8MJ01/files/rel/bom.rel
  hash: 60a04bc550e4d6a3353ce6823f9cd56719ba0514
  symbols: config/D8MJ01/bom/symbols.txt
  splits: config/D8MJ01/bom/splits.txt
- object: orig/D8MJ01/files/rel/dig.rel
  hash: e8f7c0646466e15ffc49b5f8518e9cd9e099aa51
  symbols: config/D8MJ01/dig/symbols.txt
  splits: config/D8MJ01/dig/splits.txt
- object: orig/D8MJ01/files/rel/dmo.rel
  hash: eee7b03b368bcfd2f48581b83ed4b19653ee6abd
  symbols: config/D8MJ01/dmo/symbols.txt
  splits: config/D8MJ01/dmo/splits.txt
- object: orig/D8MJ01/files/rel/dou.rel
  hash: 13dcaec1bf1c2d1c53c5138ac22b51b8a231615d
  symbols: config/D8MJ01/dou/symbols.txt
  splits: config/D8MJ01/dou/splits.txt
- object: orig/D8MJ01/files/rel/eki.rel
  hash: bc91d216bfe0019a5ab1773c6f65a77eb64656ee
  symbols: config/D8MJ01/eki/symbols.txt
  splits: config/D8MJ01/eki/splits.txt
- object: orig/D8MJ01/files/rel/end.rel
  hash: d7f53357f878f97d214d53d69be5cc07f7c20ee3
  symbols: config/D8MJ01/end/symbols.txt
  splits: config/D8MJ01/end/splits.txt
- object: orig/D8MJ01/files/rel/gon.rel
  hash: 196caeb9f6f882338a614ea1fa04286007ff44ba
  symbols: config/D8MJ01/gon/symbols.txt
  splits: config/D8MJ01/gon/splits.txt
- object: orig/D8MJ01/files/rel/gor.rel
  hash: a218a82a8889c6ad47497ae133054fac3c26c7a3
  symbols: config/D8MJ01/gor/symbols.txt
  splits: config/D8MJ01/gor/splits.txt
- object: orig/D8MJ01/files/rel/gra.rel
  hash: 401c5a3ba18fcf5c16e0529925eb41cb2327c755
  symbols: config/D8MJ01/gra/symbols.txt
  splits: config/D8MJ01/gra/splits.txt
- object: orig/D8MJ01/files/rel/hei.rel
  hash: a55d8fd871f2af8532f7507d0879027ff406b913
  symbols: config/D8MJ01/hei/symbols.txt
  splits: config/D8MJ01/hei/splits.txt
- object: orig/D8MJ01/files/rel/hom.rel
  hash: e45a1ac84415db30f47529a046974e408346cc86
  symbols: config/D8MJ01/hom/symbols.txt
  splits: config/D8MJ01/hom/splits.txt
- object: orig/D8MJ01/files/rel/jin.rel
  hash: ecb0a4b2c31ad5518cb3a0b35baf1b5c8cb6ef4a
  symbols: config/D8MJ01/jin/symbols.txt
  splits: config/D8MJ01/jin/splits.txt
- object: orig/D8MJ01/files/rel/jon.rel
  hash: 277da7990d13b590d7cbf222b0d383d42ac292e9
  symbols: config/D8MJ01/jon/symbols.txt
  splits: config/D8MJ01/jon/splits.txt
- object: orig/D8MJ01/files/rel/kpa.rel
  hash: 8793346b1c7660223307fdb5533b0fe3574d9a81
  symbols: config/D8MJ01/kpa/symbols.txt
  splits: config/D8MJ01/kpa/splits.txt
- object: orig/D8MJ01/files/rel/las.rel
  hash: 1472c328f088b3003190f8c04d6f35d8ef095e89
  symbols: config/D8MJ01/las/symbols.txt
  splits: config/D8MJ01/las/splits.txt
- object: orig/D8MJ01/files/rel/moo.rel
  hash: fb36160f5fa63acc91e96c072f7738f67989d780
  symbols: config/D8MJ01/moo/symbols.txt
  splits: config/D8MJ01/moo/splits.txt
- object: orig/D8MJ01/files/rel/mri.rel
  hash: 2b1b97deabc607791ae1b1d77330dfbebf115ba0
  symbols: config/D8MJ01/mri/symbols.txt
  splits: config/D8MJ01/mri/splits.txt
- object: orig/D8MJ01/files/rel/muj.rel
  hash: cb2cee180b75a264d0ae5e5049da7cf3c61e08d9
  symbols: config/D8MJ01/muj/symbols.txt
  splits: config/D8MJ01/muj/splits.txt
- object: orig/D8MJ01/files/rel/nok.rel
  hash: 92fc145fabd8e71641888ee5807341b15a9b8de5
  symbols: config/D8MJ01/nok/symbols.txt
  splits: config/D8MJ01/nok/splits.txt
- object: orig/D8MJ01/files/rel/pik.rel
  hash: d87f9a047e12576eb3df11fac84dc373ed850bf8
  symbols: config/D8MJ01/pik/symbols.txt
  splits: config/D8MJ01/pik/splits.txt
- object: orig/D8MJ01/files/rel/qiz.rel
  hash: d307f4d5bf7f20936497c8e40f96a92257bb0476
  symbols: config/D8MJ01/qiz/symbols.txt
  splits: config/D8MJ01/qiz/splits.txt
- object: orig/D8MJ01/files/rel/rsh.rel
  hash: d0199350912f10a9b0732faf1999986cad00c545
  symbols: config/D8MJ01/rsh/symbols.txt
  splits: config/D8MJ01/rsh/splits.txt
- object: orig/D8MJ01/files/rel/sys.rel
  hash: 1f5b8e63347710e5fade0b2c52ed265a7ed4eab6
  symbols: config/D8MJ01/sys/symbols.txt
  splits: config/D8MJ01/sys/splits.txt
- object: orig/D8MJ01/files/rel/tik.rel
  hash: 67716903e30dd1840133e4cbe31cc7d1842adfda
  symbols: config/D8MJ01/tik/symbols.txt
  splits: config/D8MJ01/tik/splits.txt
- object: orig/D8MJ01/files/rel/tou.rel
  hash: 2c0fae7e271a1e28a00bf6ab666309c5dace32e8
  symbols: config/D8MJ01/tou/symbols.txt
  splits: config/D8MJ01/tou/splits.txt
- object: orig/D8MJ01/files/rel/tou2.rel
  hash: be26a50f91dbb2692653df70222b1b1d8bc7c838
  symbols: config/D8MJ01/tou2/symbols.txt
  splits: config/D8MJ01/tou2/splits.txt
- object: orig/D8MJ01/files/rel/tst.rel
  hash: beaed74e7a76df6c1d1529c789834c1ec4c68527
  symbols: config/D8MJ01/tst/symbols.txt
  splits: config/D8MJ01/tst/splits.txt
- object: orig/D8MJ01/files/rel/usu.rel
  hash: cf87cd3a8ba4b6d388723577badbe0b45f6dd5ab
  symbols: config/D8MJ01/usu/symbols.txt
  splits: config/D8MJ01/usu/splits.txt
- object: orig/D8MJ01/files/rel/win.rel
  hash: 30d3e8cacc980de69d75cd8d4bb470e04dff65b6
  symbols: config/D8MJ01/win/symbols.txt
  splits: config/D8MJ01/win/splits.txt
- object: orig/D8MJ01/files/rel/yuu.rel
  hash: 0928195ec7b5e7c88330b44c561dc58bd1fb6464
  symbols: config/D8MJ01/yuu/symbols.txt
  splits: config/D8MJ01/yuu/splits.txt
